[build]
  base = "cryptotracker-ui"         # Path to your React project
  publish = "dist"                  # Relative path to the output folder
  command = "npm run build"

[functions]
  directory = "cryptotracker-ui/netlify/functions"  # Optional for Netlify functions
