name: Quartz Scheduler

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  run-quartz:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  
        persist-credentials: false  

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0.x"

    - name: Clean solution
      run: |
        dotnet clean
        rm -rf Cryptotracker.Worker/bin Cryptotracker.Worker/obj
        rm -rf Cryptotracker.Shared/bin Cryptotracker.Shared/obj

    - name: Setup GitHub Token
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: Restore dependencies
      run: |
        dotnet restore Cryptotracker.Worker/Cryptotracker.Worker.csproj
        dotnet restore Cryptotracker.Shared/Cryptotracker.Shared.csproj

    - name: Build
      run: dotnet build Cryptotracker.Worker/Cryptotracker.Worker.csproj -c Release --no-restore --no-incremental

    - name: Run Quartz Scheduler
      env:
        ConnectionStrings__DefaultConnection: "Host=ep-fancy-dust-a8rb01qv-pooler.eastus2.azure.neon.tech;Database=cryptotracker;Username=cryptotracker_owner;Password=8mNVfCHc7Qdw;sslmode=Require"
        ApiSettings__CoinCap__BaseUrl: "https://api.coincap.io/v2"
        ApiSettings__CoinCap__UpdateIntervalMinutes: "15"
      run: dotnet run --project Cryptotracker.Worker/Cryptotracker.Worker.csproj -c Release
